name: Email Sync Cron Job

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run_sync_function:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Trigger Supabase Edge Function
        run: curl -X POST -H "Authorization: Bearer ${{ secrets.SYNC_API_SECRET }}" ${{ secrets.SUPABASE_FUNCTION_URL }}